apiVersion: apps/v1 
kind: Deployment
metadata:
  name: jentype
  labels: 
   app: claudera
spec:
  replicas: 2
  selector:
    matchLabels:
      app: claudera
  template:
    metadata:
     labels:
       app: claudera
    spec:
      containers:
      - name: cont1
image: docker.io/cronosm4m/jentype:11



---
apiVersion: v1 
kind: Service
metadata:
  name: jenkargo
spec:
  type: NodePort
  selector:
    app: claudera
  ports:
  - port: 80  #this is for the service
    targetPort: 80 #this is for the container port.
